const mongoose = require("mongoose");

const GiveawaySchema = new mongoose.Schema(
  {
    messageId: { type: String, required: true, unique: true },
    channelId: { type: String, required: true },
    guildId: { type: String, required: true },
    startAt: { type: Number, required: true },
    endAt: { type: Number, required: true },
    ended: { type: Boolean, default: false },
    winnerCount: { type: Number, default: 1 },
    prize: { type: String, required: true },
    messages: {
      giveaway: String,
      giveawayEnded: String,
      content1: String,
      content2: String,
      content3: String,
      requirements: String,
      rolereq: String,
      serverreq: String,
      end1: String,
      end2: String,
      end3: String,
      novalid1: String,
      novalid2: String,
      drop: String,
      dropstart: String,
      dropend: String,
      winMessage: mongoose.Schema.Types.Mixed,
      embedFooter: mongoose.Schema.Types.Mixed,
      dropfooter: String,
      novalidfoo: String,
      noWinner: String,
      winners: String,
      approved1: String,
      approved2: String,
      denied1: String,
      denied2: String,
      endedAt: String,
      hostedBy: String,
    },
    thumbnail: String,
    image: String,
    hostedBy: String,
    winnerIds: { type: [String], default: [] },
    reaction: mongoose.Schema.Types.Mixed,
    botsCanWin: { type: Boolean, default: false },
    embedColor: mongoose.Schema.Types.Mixed,
    embedColorEnd: mongoose.Schema.Types.Mixed,
    exemptPermissions: { type: [String], default: [] },
    exemptMembers: String,
    bonusEntries: String,
    extraData: mongoose.Schema.Types.Mixed,
    lastChance: {
      enabled: Boolean,
      content: String,
      threshold: Number,
      embedColor: mongoose.Schema.Types.Mixed,
    },
    pauseOptions: {
      isPaused: Boolean,
      content: String,
      unPauseAfter: Number,
      embedColor: mongoose.Schema.Types.Mixed,
      durationAfterPause: Number,
      infiniteDurationText: String,
    },
    isDrop: { type: Boolean, default: false },
    allowedMentions: {
      parse: [String],
      users: [String],
      roles: [String],
    },
    reactionUsers: { type: [String], default: [] },
  },
  { timestamps: true, id: false }
);

module.exports =
  mongoose.models.giveaways || mongoose.model("giveaways", GiveawaySchema);
